# Generated by Django 3.0 on 2019-12-13 20:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.UUIDField(editable=False)),
                ('date', models.DateTimeField()),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('free_ram', models.IntegerField(blank=True, null=True)),
                ('free_disk_space', models.IntegerField(blank=True, null=True)),
                ('processes_count', models.IntegerField(blank=True, null=True)),
                ('users_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
            ],
        ),
    ]
