# Generated by Django 3.0 on 2019-12-14 18:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='computer_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='users_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
    ]
