# Generated by Django 3.0 on 2019-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191214_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='free_disk_space',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='free_ram',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='processes_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
